### ISSUE TITLE
trainedmodels request, please

### ISSUE THREAD

**Issue by Jorigorn** [UKPLab/starsem2018-entity-linking#1]
Thanks for sharing the model, nice paper.

In Readme, how can I download the  **FeatureModel_Baseline** ?
2. Take the pre-trained model FeatureModel_Baseline and extract it into a trainedmodels/ folder in the main directory of the project

Could you please share the VCG model  or can I train it on my own?

thanks .

**Comment by daniilsorokin** [comment]
Hi,

we have finally published the models and the data needed to reproduce the experiments: https://github.com/UKPLab/starsem2018-entity-linking#running-the-experiments-from-the-paper
Let me know of any further issues.

Best
Daniil
